import base64
import json
import os
import configparser
from anthropic import Anthropic


config = configparser.ConfigParser()
config_path = os.path.join(os.path.dirname(__file__), '..', '..', 'config', 'anthropic_config')
config.read(config_path)
api_key = config['Anthropic']['api_key']

anthropic = Anthropic(api_key=api_key)

model_name ="claude-sonnet-4-6"
def encode_paths(list_of_paths):
    encoded_paths=[]
    for path in list_of_paths:
        with open(path, "rb") as image_file:
            encoded_image = base64.b64encode(image_file.read()).decode('utf-8')
            encoded_paths.append(encoded_image)
    return encoded_paths
def create_img_prompt_dicts(encoded_paths):
    page_str = "Page {}."
    tuple_list =[]
    
    for index,path in enumerate(encoded_paths):
        img_dicts = {
                    "type": "text",
                    "text": page_str
                },{
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": "image/png",
                            "data": ""
                        }
                    }
        index=str(index+1)
        img_dicts[0]['text'] = page_str.format(index)
        img_dicts[-1]['source']['data'] = path
        tuple_list.append(img_dicts)
    return tuple_list


def extract_elements(lst):
    main_list = []
    for tup in lst:
        main_list.extend(tup)
    return main_list
def extract_text_from_image(list_of_paths:list):
    """
    Extract text from an image using Claude 3.5 Sonnet API.

    Args:
        image_path (str): Path to the image file.

    Returns:
        Dict[str, Any]: JSON response containing extracted text and metadata.
    """
    # Read API key from config file
    
    encoded_paths = encode_paths(list_of_paths)


            
    img_dicts = create_img_prompt_dicts(encoded_paths)

    tools = [
    {
        "name": "extract_invoice_info",
        "description": "Extracts key information from the invoice.",
        "input_schema": {
            "type": "object",
            "properties": {
                "vendor": {"type": "string", "description": "The invoice vendor."},
                "purchase_order_number": {"type": "string", "description": """The purchase order number. (This is a unique identifier 
                        that is generated by the buyer to track and reference a particular transaction throughout the procurement process)"""},
                "invoice_number": {"type": "string", "description": "The invoice number."},
                "invoice_date": {"type": "string", "description": "The date of the invoice."},
                "invoice_due_date": {"type": "string", "description": "The due date of the invoice."},
                "ship_to_address": {"type": "string", "description": "The ship to address of the invoice."},
                "vendor_address": {"type": "string", "description": "The vendor address on the invoice."},
                "invoice_items": {"type": "array","items":{"type":"object", "properties":{
                    "Quantity": {"type": "string", "description": "the quantity of the item"},
                    "item_Description": {"type": "string", "description": "item description"},
                    "unit_price": {"type": "string", "description": "item unit price"},
                    "item_total": {"type": "string", "description": "the item net total"}
                    }}},
                "items_subtotal": {"type": "string", "description": "The invoice subtotal"},
                "invoice_tx": {"type": "string", "description": "The invoice tax"},
                "invoice_total": {"type": "string", "description": "The invoice total"},
                "freight": {"type": "string", "description": "The freight charges of the invoice, if there are any."},
                "discount": {"type": "string", "description": "The amount of the discount, if there is any."}
                
            
            },
            "required": ["vendor", "invoice_number", "invoice_date", "invoice_due_date", "ship_to_address", "vendor_address", "invoice_items", "items_subtotal", "invoice_tx", "invoice_total","freight","discount"]
        }
    }
]
    
    img_dicts = extract_elements(img_dicts) # remove the dicts from the tuples
    
    img_dicts.insert(0,{
                        "type": "text",
                        "text": """Analyze the invoice image and extract the key data requested by the tool.Use the extract_invoice_info tool to provide the extracted information. Adhere to the following instructions when using the function: 
                            - If the image is not an invoice or data missing still return using the tool with values of 'Not available'.
                            - If there is no PO # present on the invoice, there are some alternatives. The best numbers for 
                                this field are as follows (select the first in this list available on the invoice):
                                1. PO number. 
                                2. Order number.
                                3. Customer number."""
                                })
    print(img_dicts)
    response = anthropic.messages.create(
        model=model_name,
        max_tokens=4000,
        tools=tools,
        messages=[
            {
                "role": "user",
                "content": img_dicts
                            }
                            ]
                        )
            

                                                                                                            
    # Parse and return the JSON response
    for content in response.content:
        if content.type == 'tool_use':
            return content.input
    return None


def generic_claude_function(system_prompt,user_prompt):

    message = anthropic.messages.create(
        model=model_name,
        max_tokens=4000,
        temperature=0,
        system=system_prompt,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": user_prompt
                    }
                ]
            }
        ]
        )
    return message.content[0].text